import Head from "next/head";
import { useState, useEffect } from "react";
import BannerDiv from "../components/Site/Home/banner";
import ClassesCard from "../components/Site/Home/ExploreClasses/ClassesCard";
import Testimonial from "../components/Site/Home/Testimonial";
import Phone from "../components/Site/Home/HowWeTeach/Phone";
import style from "../styles/Home.module.css";
import VRSection from "../components/Site/Home/VRSection";
import Science from "../components/Site/Home/Science";
import getClasses from "../utils/adapters/get/get";
import AOS from "aos";

function Home() {
  const [classes, setClasses] = useState();

  useEffect(() => {
    AOS.init();
    AOS.refresh();
  }, []);
  // let arr=[
  //   {
  //     class:'Class 9th',
  //     img:'class9.png',
  //     color:"linear-gradient(99deg, #df335f, #e97a54)"

  //   },{
  //     class:'Class 10th',
  //     img:'girl.png"',
  //     color:"linear-gradient(99deg, #df335f, #e97a54)"
  // class1={"Class 10th"}
  // img={"girl.png"}
  // color={"linear-gradient(99deg, #5474ED, #1BB8FC)"}
  //   }
  // ]
  useEffect(() => {
    get();
  }, []);
  async function get() {
    let classes = await getClasses();
    setClasses(classes);
  }

  return (
    <>
      <Head>
        <title>Upmarks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BannerDiv />

      <section className={style.ExploreClassSection}>
        <h2 className={`${style.ExploreH2} text-8xl`} data-aos="zoom-in">
          Discover our mad dream of making the world Study!
        </h2>

        <div className="">
          <div className={` ${style.CardContainer} px-4 p-4 flex`}>
            {classes &&
              classes.data.map((ele, index) => (
                <ClassesCard
                  // class1={"Class 9th"}
                  // img={"class9.png"}
                  classDetail={ele}
                  key={index}
                  // color={"linear-gradient(99deg, #df335f, #e97a54)"}
                />
              ))}
          </div>
        </div>
      </section>
      {/* <PopularSubject /> */}
      <Science />
      {/* <ExploreVRGames /> */}
      <VRSection />
      <Phone />
      {/* <Map /> */}
      <Testimonial />
    </>
  );
}

{
  /* <ClassesCard
              class1={"Senior"}
              color={"linear-gradient(99deg, #9d73e1, #f596e1)"}
            />
            <ClassesCard
              class1={"Upper Senior"}
              color={
                "linear-gradient(315deg, rgb(59, 183, 143) 0%, rgb(11, 171, 100) 74%)"
              }
            /> */
}

// export const getServerSideProps = async () => {
// const queryClient = new QueryClient();
// const STALE_TIME = 10000;
// await queryClient.prefetchQuery("sdd", fetchPosts, {
//   staleTime: 5000,
//   // refetchOnMount: false,
//   // cacheTime: 5000,
// });
//   let response = await getClasses();
//   console.log("res ", response);

//   return {
//     props: {
//       classes: response,
//     },
//   };
// };
//   console.log("in serve func");
//   let response = await getClasses();
//   return {
//     props: {
//       classes: response,
//     },
//   };
// };

export default Home;

// export { getServerSideProps };
// export async function getStaticProps(context) {
//   if (context.query) {
//     let { data } = context.query;
//     if (data != null) {
//       console.log("in if cond");
//       const data2 = JSON.parse(data);
//       console.log("Wrapp", data2);
//       let [err, curriculam] = await request(
//         "GET",
//         `/game/content/subject-modules?classId=${data2.classId}&subjectId=${data2.subjectId}`
//       );
//       console.log("curr", curriculam);
//       if (curriculam) {
//         return {
//           props: {
//             classes: JSON.parse(JSON.stringify(response)),
//             curriculam: JSON.parse(JSON.stringify(curriculam)),
//           },
//         };
//       }
//     }
//   }
//   // console.log("wrapper", );

//   let [err, response] = await request("GET", "/game/curriculum");

//   return {
//     props: { classes: JSON.parse(JSON.stringify(response)) },
//   };
// }

// export { getServerSideProps };

// export default NavbarWrapper(Home);
